name: travelr
description: Track the countries you’ve visited
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  modal_progress_hud: ^0.1.3
  syncfusion_flutter_maps: ^19.1.57-beta.1
  provider: ^4.1.0
  country_icons: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/